### ISSUE TITLE
could you add some check style report?

### ISSUE THREAD

**Issue by longbai** [gojp/goreportcard#123]
like java checkstyle, or https://github.com/qiniu/checkstyle

**Comment by hermanschaaf** [comment]
My concerns: There seems to be some overlap between this tool and gofmt and golint ("camel_name", "formated"), and most of the other criteria are rather subjective ("file_line", "params_num", "results_num"). 

Furthermore, the tool requires a json config file to specify ignored files in a directory. We make an attempt to ignore generated files, and since we cannot expect projects to have this json file, we will have to generate one and place it in the project before running the tool. It's not impossible, but it feels hacky. It would be nicer if we could specify a list of files to be checked from the command line.

That said, I can see how this can be a useful way to measure code style. I would certainly prefer projects I read to conform to these styles. But this tool does require a lot of parameters, and I can already foresee users complaining that the rules we choose are inappropriate for their case :)
