### ISSUE TITLE
Files are not refreshed even after new updates

### ISSUE THREAD

**Issue by t3rm1n4l** [gojp/goreportcard#133]
goreportcard reports invalid files from old changes:

https://goreportcard.com/report/github.com/t3rm1n4l/nitro talks about memdb.go which does not exist in the latest repo anymore. I have tried refreshing couple of times and it did not help.

**Comment by t3rm1n4l** [comment]
Could you guys please remove the repo cache for github.com/t3rm1n4l/nitro ?

**Comment by hermanschaaf** [comment]
@t3rm1n4l sorry I haven't had a chance to look into this sooner. It seems like the `diskstore` branch is checked out on our server - was that the default branch at some point? Just trying to figure out the root cause here.

In any case, I checked out the master branch and refreshed it - looks good now. Let me know if you run into any more issues.

**Comment by t3rm1n4l** [comment]
Thanks a lot
