### ISSUE TITLE
Make a cmd/reportcard binary to be able to get our score localy

### ISSUE THREAD

**Issue by hydroflame** [gojp/goreportcard#134]

**Comment by hermanschaaf** [comment]
I like this idea, and would use it myself!

If you want it to happen soon, feel free to open a PR :smile:  Otherwise I'll probably implement it some time in the coming month when I have some free time.

**Comment by jfeltesse-mdsol** [comment]
related to https://github.com/gojp/goreportcard/issues/28 ?

**Comment by hermanschaaf** [comment]
@jfeltesse-mdsol Yes, very related to #28. In order to properly implement the feature in this ticket, we first have to refactor the code a bit, which should close #28. I started working on this a while back but never got round to finishing it. And I won't risk any further promises when I'll pick it up again :)

**Comment by xh3b4sd** [comment]
Any update on this? I would like to integrate the command for my local build process.

**Comment by patyogesh** [comment]
I can take this if no one has been working on this actively.

**Comment by shawnps** [comment]
@patyogesh that would be great. If you open a PR I'm happy to review.
