### ISSUE TITLE
"Could not go get the repository."

### ISSUE THREAD

**Issue by purpleidea** [gojp/goreportcard#138]
I'm unable to use this with https://github.com/purpleidea/mgmt/

I get the following error message: 

```There was an error processing your request: Could not go get the repository.```

Any help understanding why I get the error would be appreciated. Thanks!

**Comment by hermanschaaf** [comment]
Hi @purpleidea, 

I fixed this case manually, you can see the report at https://goreportcard.com/report/github.com/purpleidea/mgmt now. Thanks for reporting!

The issue seems to have stemmed from two dependencies, `github.com/coreos/etcd/client` and `github.com/coreos/etcd/pkg/capnslog`. We already had a version of `github.com/coreos/etcd` pulled, but this version somehow did not include those directories. And because the parent dir was already there, `go get` gives up. I fixed it by removing `etcd` and then rerunning the `go get`. It's hard to pinpoint exactly how this arose, and it seems like it's a rare enough event that we can fix it manually for now when it happens...

**Comment by purpleidea** [comment]
@hermanschaaf Glad to know it wasn't something I did wrong. Now to fix up the problems on my "report card" ;)

Thanks!

**Comment by xor-xor** [comment]
I have the same issue with https://github.com/allegro/ralph-cli - when I feed it to goreportcard launched locally, everything is fine (i.e. it produces the report), but when I feed it to https://goreportcard.com, I get the same error as OP.

**Comment by berezovskyi** [comment]
I also get the same issue with github.com/berezovskyi/ldpserver

**Comment by mozillazg** [comment]
Same here: 
* https://github.com/mozillazg/go-slugify
* https://goreportcard.com/report/github.com/mozillazg/go-slugify

**Comment by monder** [comment]
It seems https://github.com/monder/rkt-sidekick has the same.

**Comment by hermanschaaf** [comment]
@monder @xor-xor It works now; was a known caching issue first, and then our server ran out of disk space, sorry for not looking into it sooner. [rkt-sidekick](https://goreportcard.com/report/github.com/monder/rkt-sidekick) [ralph-cli](https://goreportcard.com/report/github.com/allegro/ralph-cli)

@berezovskyi In the `ldpserver` case the error is something different. This is what I see in the logs: 

`Go get error log: package ldpserver/web: unrecognized import path "ldpserver/web" (import path does not begin with hostname)`

If I try to run  go get locally from my machine, it also fails with that error.

**Comment by xor-xor** [comment]
@hermanschaaf - thanks!

**Comment by purpleidea** [comment]
@hermanschaaf I tried to "refresh" the repository, since I've fixed some issues and wanted to "update my score". Unfortunately I still get the same `go get` error.

**Comment by medzin** [comment]
I also have problem with refreshing repo stats. When I click "Refresh now" button I get following error: "There was an error processing your request: Could not go get the repository." 

My repository: https://github.com/medzin/zb

**Comment by purpleidea** [comment]
As of 5 minutes ago, this seems to be fixed. Closing...

**Comment by pavel-paulau** [comment]
I am still seeing this issue:

https://goreportcard.com/report/github.com/pavel-paulau/rollercoaster

**Comment by hermanschaaf** [comment]
Thanks @pavel-paulau. Yes, I could go get your repo locally, so this issue is not yet resolved yet. I'll re-open it for now.

**Comment by Dieterbe** [comment]
same issue with https://goreportcard.com/report/github.com/raintank/metrictank thanks!

**Comment by hermanschaaf** [comment]
I finally got around to fixing this issue (in [this commit](https://github.com/gojp/goreportcard/commit/a2b2dbdbc784aeebab550a75d252925405558522)). @pavel-paulau @Dieterbe both your repos work now. Let me know if you encounter any other issues!

As an added bonus, since we no longer use `go get`, all checks will actually happen significantly faster.

**Comment by Dieterbe** [comment]
thank you very much!
