### ISSUE TITLE
Repo clone fails if gopkg.in a direct or transitive dep

### ISSUE THREAD

**Issue by akutz** [gojp/goreportcard#144]
I had a conversation with Gustavo Niemeyer, the caretaker of Gopkg.in, around the beginning of June (note the thread below starts with the oldest e-mail at the top):

> On May 26, 2016 4:02 PM, "Andrew Kutz" wrote:
> 
> Hi,
> 
> Someone there decided to edit your matching and trailing slashes are now rejected. This causes issues since Go adds trailing slashes. I fixed my own build by adding this to `.travis.yaml`:
> 
> ```yaml
> before_install:
>   - git config --global 'url.https://gopkg.in/yaml.v1.insteadof' 'https://gopkg.in/yaml.v1/'
>   - git config --global 'url.https://gopkg.in/yaml.v2.insteadof' 'https://gopkg.in/yaml.v2/'
>   - git config --global 'url.https://gopkg.in/fsnotify.v1.insteadof' 'https://gopkg.in/fsnotify.v1/'
> ```
> 
> 
> Just FYI

--

>> On Jun 1, 2016, at 12:05 AM, Gustavo Niemeyer wrote:
>> 
>> Thanks, Andrew.
>> 
>> Suspect this is actually a change in the Go's HTTP server itself, since the code didn't actually change on this area, but was rebuilt with a newer Go release.
>> 
>> Will investigate.

--

>>> Hi Gustavo,
>>> 
>>> FWIW I am using Go 1.6.2 on my end as well. Now, I was using it with Glide and I'm not sure with what Stdlib it was compiled. I suppose a raw go get would determine where the bug is.

--

It appears `go get` adds a trailing slash and someone just made a config change on the gopkg servers to reject trailing slashes for a URl, and due to the way gopkg.in handles incoming HTTP requests, thanks to the underlying Go HTTP server, it fails:

```bash
$ curl -vvv http://gopkg.in/yaml.v2/ && echo
*   Trying 107.178.216.236...
* Connected to gopkg.in (107.178.216.236) port 80 (#0)
> GET /yaml.v2/ HTTP/1.1
> Host: gopkg.in
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Date: Tue, 26 Jul 2016 00:25:41 GMT
< Content-Length: 71
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host gopkg.in left intact
Unsupported URL pattern; see the documentation at gopkg.in for details.
``` 

This issue appears to be why some projects, such as github.com/emccode/rexray, github.com/emccode/libstorage, and github.com/akutz/gofig are failing at the repository step on Go Report Card. My project github.com/akutz/goof, on the other hand, *does* work, likely due the fact that its import paths do not directly or transitively include a gopkg.in-hosted package.

**Comment by hermanschaaf** [comment]
This is interesting, thanks! This issue has been bugging us for a while now, and you could be right that this is in fact the root cause. I'll have to look into it soon. 

Right now I'm actually considering circumventing "go get" and going back to directly pulling repos with the appropriate SCM (git, hg, etc). This would also have the advantage that we won't be pulling in all the dependencies every time as well, which makes it both faster and easier to debug.

**Comment by akutz** [comment]
An easy way to test it is to add the git URL redirects as mentioned via the email thread above. Add those to the node that is doing the go get and you should be good to go. FWIW, it's a Git issue on the server side, NOT a Go issue, so I'm not sure bypassing go get will help if the URLs are still constructed with the trailing slash. Hence the need to alter it at the Git level.

**Comment by hermanschaaf** [comment]
Hi @akutz, we recently made some changes to pull repos directly via VCS, which fixed the `Could not go get repository` error many repos were getting. Other than purposefully adding a slash to the end of the repo name when entering it in the input box on goreportcard.com (which does fail, and we can probably handle that), is there a case you can point out where goreportcard still fails, in particular packages hosted on gopkg.in? All the ones I have tried so far work. 

For example, entering `http://gopkg.in/yaml.v2` works, and so does `gopkg.in/yaml.v2`, but `gopkg.in/yaml.v2/`, does not, presumably because of the trailing slash. The same goes for any other host too though, for example, `github.com/quickfixgo/quickfix/` (with trailing slash) also fails.

**Comment by akutz** [comment]
And voila, it works!

- [REX-Ray](https://goreportcard.com/report/github.com/emccode/rexray)
- [libStorage](https://goreportcard.com/report/github.com/emccode/libstorage)

Thank you @hermanschaaf!
