### ISSUE TITLE
errcheck without any errors is reported as '0%'

### ISSUE THREAD

**Issue by fd0** [gojp/goreportcard#147]
Hi,

for my project [restic](https://github.com/restic/restic) the errcheck check does not return anything, but it is reported as `0%`: https://goreportcard.com/report/github.com/restic/restic#errcheck

![2016-07-29-213038_1135x190_scrot](https://cloud.githubusercontent.com/assets/123276/17261033/27d54880-55d4-11e6-81dd-c899b0b97545.png)

I think that's wrong, the percentage should be the other way around...

**Comment by hermanschaaf** [comment]
Strange; this normally happens when a check fails to run. Whatever the reason was for the failure before though, I refreshed it just now and there were no errors:

![screenshot from 2016-07-30 06 57 08](https://cloud.githubusercontent.com/assets/1121616/17265610/dcb9b3d2-5622-11e6-8868-d47981fd4c38.png)

**Comment by hermanschaaf** [comment]
The errcheck test is reasonably new and is giving some issues on certain repos (can be slow, or not report missing error checks), so I'm disabling it for now. We can re-enable it once the issues are sorted out. 

To better address this in the future, from now on if a test fails because of a timeout or other error, the error will be reported in the UI:

![gocyclo error](https://cloud.githubusercontent.com/assets/1121616/17356503/63c630de-598a-11e6-8791-08686ce5f110.png)

**Comment by fd0** [comment]
Thanks for taking a look! Great project by the way :smiley:
