### ISSUE TITLE
toplist on website seems to be screwed

### ISSUE THREAD

**Issue by xh3b4sd** [gojp/goreportcard#160]
I was surfing around and found this. Does not look like it is intended. Further there is no re-index button or something like this. Interestingly, when clicking on the weird and duplicated "highscore" links, these repos do not exist at all. 

<img width="1237" alt="screen shot 2016-10-10 at 00 47 15" src="https://cloud.githubusercontent.com/assets/552769/19224282/2b643424-8e83-11e6-9a65-2948dd65c359.png">

**Comment by shawnps** [comment]
This was @karolgorecki messing with the list by creating multiple repos with lots of Go files in them. You'll notice each of those repos have different names. I might just remove the high scores list altogether considering now everyone will know how to break it.

**Comment by karolgorecki** [comment]
Hi, sorry that I've broke you high score page.
You score is calculated only by number of files + the score for each file. You can easily create many files with empty packages like `pacakge foo1`, `package foo2`. They will get 100%.

Also you can only rename the existing repo and submit it again so it's easy to duplicate. After removing repo from  my gh account I cannot refresh it/remove it because it doesn't exists.

**Comment by shawnps** [comment]
@karolgorecki no need to apologize, but it would be really useful to us if you opened an issue here after doing something like this. We work on this for free and for the community so we appreciate any help we can get.

We might add a GitHub star minimum to the high score repos which I guess would make it harder to game? But I also might just remove the page because now that this is out there it's probable that someone else will try.

**Comment by xh3b4sd** [comment]
I think having a feature that makes sure the list of indexed repositories is refreshed from time to time makes totally sense. Repositories can disappear. Requiring a certain amount of stars to be listed makes also sense somehow. I like having this list. People check that and make sure they appear there. Removing it would regress the product a little bit.

**Comment by endophage** [comment]
Like the idea of requiring some number of stars to get listed on high scores. Dropped in just to propose (or I guess second) the idea to periodically ping the repos and remove those that don't exist anymore.

**Comment by xh3b4sd** [comment]
Is there any update on this issue? I see that the toplist is still screwed. Is there a way to get rid of the fake listings?

**Comment by erikh** [comment]
Maybe make the files considered as a "file" a minimum length?
