### ISSUE TITLE
To integrate Go's unit test report

### ISSUE THREAD

**Issue by penhauer-xiao** [gojp/goreportcard#171]
I recommended to integrate Go's unit test report (GoConvey: https://github.com/smartystreets/goconvey), the Go's unit test report is very important and useful.

**Comment by shawnps** [comment]
@penhauer-xiao this looks like a library that builds on top of `go test`? I'm not sure how we'd use this, it seems like it would depend on whether our users are running GoConvey or not. In any case I don't think we have plans to add unit test coverage at the moment, since many of our users have quite large repos and it would just be impossible with our current architecture to run tests efficiently. Thanks for filing an issue though.
