### ISSUE TITLE
Support Go 1.9 or ignore go1.9 build tag?

### ISSUE THREAD

**Issue by mafredri** [gojp/goreportcard#189]
Hi,

would it be possible to add support for Go 1.9? I realize it's in beta right now, so a more reasonable approach could be to ignore files with `// +build go1.9`.

Thoughts?

I'm asking because Go Report Card is currently failing on [one of my repositories](https://goreportcard.com/report/github.com/mafredri/cdp) due to type aliases.

**Comment by mafredri** [comment]
I noticed goreportcard is using `gometalinter` so I tried locally and noticed that `gofmt` is not broken (via gometalinter) for me at least. Perhaps I have a newer version or the `go1.9beta2` release is doing some magic. My primary go version is still `go1.8.3`.

I reported the `go vet` errors: https://github.com/alecthomas/gometalinter/issues/323.

As a workaround, this might work:

```console
$ gometalinter --disable-all --enable=vet --linter='vet:go tool vet -printfuncs=Infof,Debugf,Warningf,Errorf {path}:PATH:LINE:MESSAGE'
```

However, I'm not sure of the repercussions, or in what way (if any) `go1.9beta2` plays a role.

**Comment by kataras** [comment]
Hello guys && @shawnps 

Go 1.9 released, we need a correct reportcard, my own web framework drops from A+ to B because of type alias inside a file with restrict access to go 1.9, I assume that vet tools don't care about that and count it to the overall result no matter what but now that Go 1.9 released I think that if you just upgrade the host's machine Go Programming version and the vet tools then it will work

Thank you!

**Comment by shawnps** [comment]
I will take a look tonight

**Comment by kataras** [comment]
You're awesome, thank you very much for your work

**Comment by shawnps** [comment]
@kataras should be all set: https://goreportcard.com/report/github.com/kataras/iris

**Comment by shawnps** [comment]
@mafredri should be fixed for you as well: https://goreportcard.com/report/github.com/mafredri/cdp

Thanks for reporting!
