### ISSUE TITLE
We need to support git repositories outside of github.com 

### ISSUE THREAD

**Issue by tariq1890** [gojp/goreportcard#194]
Thank you for this great tool! We have been using this in our Github Enterprise repositories and integrated with our CI systems. 

I have noticed that the repository filename links aren't generated for non-github (like gitlab) and github enterprise repos. I have however managed to get it working by adding extra conditional statements to account for our enterprise repositoriy prefixes.

I feel it would be good provide known repository prefixes in a config file and have goreportcard read that. This way we can ensure support for multiple git online repos like gitlab, github enterprise etc (and not just github.com)

If you guys are okay with the direction of a config file, I am happy to submit a PR.

**Comment by shawnps** [comment]
@tariq1890 just to clarify, you mean you're running an instance of Go Report Card internally so that you can use it on your GitHub Enterprise repositories? Also I don't know much about GitLab - is that something you host internally as well?

If you only use one (GHE or GitLab) I might prefer a flag for this rather than a config file.

**Comment by tariq1890** [comment]
Yes. GitLab is another repository.  We'd use goreportcard for both GitHub and GHE. Right now we've added extra conditional statements to support our GHE. Using a config file would help make goreportcard more extensible. Since only the GHE user knows the GitHub Enterprise details, they can add the details in the config file.

**Comment by shawnps** [comment]
@tariq1890 if you make a PR when you have some free time, I'd be happy to take a look. Please just make it so the config is optional, in other words nothing should change the way we deploy goreportcard.com. I'd also like to avoid vendoring a big config-parsing library if possible. JSON might be fine since this config should be really small. A sample config or addition to the README etc. would be really helpful too.

**Comment by tariq1890** [comment]
Sure. I can get around to doing that.

**Comment by tariq1890** [comment]
@shawnps I just realized that the tweak I had made was in vcs.go to get the GitHub ENterprise links working.

Looks like the change is required in golang's tools repository. I guess we can close this issue

**Comment by shawnps** [comment]
@tariq1890 you mean you patched `vcs.go` so Go Report Card would work with GHE repositories in general, not just to fix the links? I haven't tried running Go Report Card against a GHE repo so I'd be curious to know what happens when you do. 

If you have any ideas on this let me know and we can try to figure something out.

**Comment by tariq1890** [comment]
Yes, I had patched vcs.go to add our Github Enterprise URL Regex. If you have had a look at the vcs.go, you would've noticed the list of the vcs paths that are recognized by the go tools library. My solution was to simply add the GHE URL pattern to that hardcoded list of recognized VCS URL patterns.

I do have an idea. First off, I am puzzled that vcs.go uses such a roundabout way to go about the whole git repository cloning. We should take advantage of the fact that most repositories regardless of the hosting service (be it GitHub, GHE, BitBucket or GitLab) are essentially git repositories. Take IntelliJ for example, it issues a git ls-remote call internally to test a connection and then issues a git clone command to import that repository. No regex checks whatsoever. This is why we can easily clone GHE, BitBucket and GitHub repos easily via IntelliJ without requiring any special coniguration beforehand. My 2 cents :).

**Comment by tariq1890** [comment]
@shawnps Thoughts?

**Comment by shawnps** [comment]
Hey @tariq1890 sorry not sure I totally follow - I believe we're using VCS because we can't assume everyone will be using `git` for their Golang packages. For example people might be using Mercurial, or Subversion, etc.

**Comment by tariq1890** [comment]
I agree with what you have to say. But VCS has this method of regex validation. I don't think the best approach is to assume a pattern for all of these repositories. This is the main reason that GitHub Enterprise URLs fail as they don't match the patterns declared/defined in VCS.go.

A better way of validating would be to provide a ping command to see if the repository connection is established. For eg:- For git repos we use the git ls-remote command.

How about for any go get path the user enters, we issue the ping commands from each repository type (SVN, Mercurial, Git etc). This continues in a loop until a successful repository connection is established thereby determining the repository type as well. Let me know If I need to clarify more on this.

If you're okay with this idea, I can write a go library to achieve this.

**Comment by koalalorenzo** [comment]
up!
