### ISSUE TITLE
UI Issues that need fixing

### ISSUE THREAD

**Issue by tariq1890** [gojp/goreportcard#197]
Here are a few UI issues that I have found

1. There is no input validation. We should validate for an empty string and throw an error.
2. The placeholder holder text should disappear on focus/click.
3. Rather than populating error messages as notifications, we can show error messages as alert dialogs instead. Right now errors stick to the notification div panel and don't disappear. They occupy space in and push the rest of the site body down. 

![image](https://user-images.githubusercontent.com/2658224/29265947-c63cbf5a-8097-11e7-81c0-719f8da54bd1.png)

If you're okay with these changes, I can submit a PR.

**Comment by shawnps** [comment]
@tariq1890 Personally I don't think we need a fix for no. 1, the error we show is good enough for me. And for no. 3 I think I'd find a popup (if that's what you're suggesting) more annoying than what we have currently.

@hermanschaaf thoughts?

**Comment by hermanschaaf** [comment]
For no 1: I agree with @tariq1890 here, some validation on an empty string would be a nice change, even if it is just a nicer error message.

No. 2 is not an issue for me, that's just default browser behavior (it disappears as soon as you type something, which I think is fine)

For no 3: I think a valuable change would be to show only the latest notification, not a whole long list like in the screenshot. Other than that like @shawnps I'm also pretty happy with how it is now (pushing the body down instead of a popup or other kind of alert)

**Comment by shawnps** [comment]
@tariq1890 if you still want to make a PR, feel free to go with @hermanschaaf's comments :)

**Comment by tariq1890** [comment]
Sure! I'll create the PR
