### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by GoLangsam** [gojp/goreportcard#207]
When investigating #113 I installed on Windows and it worked mysteriously well!
( notwithstanding Your disclaimer in Your ReadMe ;-) 

This is mostly because go is very tolerant about slashes when used directly as arguments e.g. to ioutil.ReadDir or `os.MkdirAll("_repos/src/github.com", 0755)`

Just: some things do ***not*** work yet, e.g. gofmt.

As far as I can see, it **only** needs use of path/filepath at places such as
 `filename = strings.TrimPrefix(filename, "_repos/src")`.
Simple refactoring.

As I'm a happy user of Your site & service, I'm ready to volunteer.
( And also keep an eye on it's working fine under M$Win ) 

If You like, I'll be happy to provide You with a PR - please let me know.

**Comment by shawnps** [comment]
@GoLangsam since we run this app on Linux, this really isn't a priority for us, but if you want to make a PR and everything is backwards-compatible, I don't see why we wouldn't merge it unless it is a massive diff. If it's just `path/filepath` stuff, I'd be interested to see a PR.

Sorry for our "_ignorant_ code" 😂

**Comment by GoLangsam** [comment]
@shawnps You have an interesting way to play with colons `":"` :-)

Please teach me:

- What does `AddError` hope to receive?

- What does `getFileSummaryMap` try to achieve when doing
``
```
filename := strings.Split(out.Text(), ":")[0]
``` 

See enclosed annotated panic
[trace000.txt](https://github.com/gojp/goreportcard/files/1335681/trace000.txt)
