### ISSUE TITLE
My Badge isn't showing up properly

### ISSUE THREAD

**Issue by ddrechse** [gojp/goreportcard#231]
Hi,

Look here and u will see an error goreport card
https://github.com/ddrechse/navarkos/blob/master/README.md

Click the goreportcard badge link and it is an A+ grade
https://goreportcard.com/report/github.com/oracle/navarkos

I copied the markup from this page.  I don't know why it doesn't work
I don't think its a caching issue.  I have had others checking

Help

Tnx
Doug

**Comment by hermanschaaf** [comment]
Hi Doug, thanks for bringing this to our attention. I wonder if it was a temporary issue (sometimes Github caches images more aggressively than they should), because I can see it when I load the page:

![screenshot from 2017-12-08 16-40-34](https://user-images.githubusercontent.com/1121616/33775560-b2580512-dc36-11e7-98af-4dd56dace0cb.png)

**Comment by ddrechse** [comment]
Thanks for looking at it
Please try here when u get a chance, this is the "real" repo
https://github.com/oracle/navarkos

If that looks good, close the ticket and I will follow up w github

Tnx
Doug

**Comment by hermanschaaf** [comment]
Still looks good:

![screenshot from 2017-12-08 17-30-38](https://user-images.githubusercontent.com/1121616/33777642-8d1e7432-dc3d-11e7-8c4c-3bab79394d0e.png)

**Comment by ddrechse** [comment]
ok thanks for checking.  I'll look into github caching

Regards
Doug

**Comment by ddrechse** [comment]
Just an FYI. We got around the github cache by appending a ? to the url
[![Go Report Card](https://goreportcard.com/badge/github.com/oracle/navarkos?)](https://goreportcard.com/report/github.com/oracle/navarkos)

Doug
