### ISSUE TITLE
ineffassign reporting is incorrect

### ISSUE THREAD

**Issue by didenko** [gojp/goreportcard#232]
`Ineffassign`'s negative check reported as positive. At the refreshed repo, `goreportcard` detects an `ineffassign` positive:

![2017-12-14 18 48 17](https://user-images.githubusercontent.com/99670/34021494-dbf587be-e0ff-11e7-99c3-38d3adb8f754.jpg)

While `ineffassign` itself does not detect any errors:

![2017-12-14 18 47 12](https://user-images.githubusercontent.com/99670/34021511-f177b0da-e0ff-11e7-8583-0880df39fe5c.jpg)

This looks suspiciously similar to the behavior mentioned in #202, I hope it has the same root cause.

**Comment by yangwenmai** [comment]
I also have this problem.
![tidb_gojp](https://user-images.githubusercontent.com/1710912/36636332-c81e87b6-19ff-11e8-8561-e3720564743e.png)

**Comment by sebastianst** [comment]
I can confirm that this problem is still there https://goreportcard.com/report/github.com/perun-network/go-perun#ineffassign

It is the same pattern: goreportcard's ineffassign claims that there is an unused `err` variable (which is evidently used in the next line though). Running `ineffassign` locally doesn't show any errors.
