### ISSUE TITLE
report icon on markdown README not refresh!

### ISSUE THREAD

**Issue by davyxu** [gojp/goreportcard#244]
Hi, heres my github(https://github.com/davyxu/cellnet)  using goreportcard

I have updated the goreport page(https://goreportcard.com/report/github.com/davyxu/cellnet)
but the github page always no update and shows level C

Why?

**Comment by hermanschaaf** [comment]
Hi @davyxu , the image is cached by github on your browser. The issue is on the Github side, and it's likely that if you clear your cache you'll see that the correct value:

![screen shot 2018-04-23 at 1 03 45 pm](https://user-images.githubusercontent.com/1121616/39125446-e2aa2828-46f6-11e8-9405-2e9c2a8e831f.png)

We set headers on the image to prevent caching, but github doesn't always respect that unfortunately.
