### ISSUE TITLE
Add check for semantic version tags

### ISSUE THREAD

**Issue by leighmcculloch** [gojp/goreportcard#253]
With go1.11 modules (`go mod`) enter as an experiment, and previously `dep` has been the recommended approach to dependency management. Both put significant value on go projects tagging their releases with semantic versions, or [semver](https://semver.org/).

I think it's worth adding a check to goreportcard that signals that there is value to tagging versions.

I'd be open to adding the commit to add this feature, if you folks think this is worthwhile.

**Comment by thepudds** [comment]
Wanted to briefly bounce this to see what the latest thinking is, especially since it sounds like @leighmcculloch had volunteered to do the work. 

FWIW, I think there is a lot of value in this, especially given Go modules are [planned](https://blog.golang.org/modules2019) to be enabled by default in Go 1.13, which is not too far away.

Go modules work much better in practice if more of the broader Go ecosystem start using semver tags, as @leighmcculloch said above, and it seems goreportcard could help nudge the community forward.

Related question -- what is the general process for getting some level of agreement to proceed on a new check? Is it effectively "send a PR if there are no objections"?  The "Contributing" section of the readme says:

> **Contributing**
> 
> Go Report Card is an open source project run by volunteers, and contributions are welcome! Check out the Issues page to see if your idea for a contribution has already been mentioned, and feel free to raise an issue or submit a pull request.

**Comment by leighmcculloch** [comment]
I haven't started on this yet. I was waiting for some indication from @gojp / @hermanschaaf / @shawnps that it would be accepted before putting any time into it. I'm still happy to do it but if anyone else is keen go for it.
