### ISSUE TITLE
Proposal: Add option to generate badges from the cli

### ISSUE THREAD

**Issue by georgeok** [gojp/goreportcard#268]
It would very convenient for CI environments to have a badge generated by the `goreportcard-cli`. The badge should go to the stdout as an svg file or an image file to a specified output file. I am quite happy to implement if the authors like the idea.

**Comment by gboor** [comment]
+1 to this idea, but then you'd also have to generate the report HTML to link to, I guess. That way the whole functionality can be used in closed CI/CD pipelines.

Since the whole thing is open source, this should not be overly difficult. Another option is just self-hosting it.

I'm looking into using this for a series of private repos and I'm not sure yet what the best way will be, but I like the idea of using the cli to generate all assets.
