### ISSUE TITLE
Untraceable vet error

### ISSUE THREAD

**Issue by pascaldekloe** [gojp/goreportcard#275]
“ExampleMust1LabelHistogram refers to unknown identifier: Must1LabelHistogram (vet)”
— https://goreportcard.com/report/github.com/pascaldekloe/metrics#go_vet

The function exists, go doc [links the example](https://godoc.org/github.com/pascaldekloe/metrics#example-Must1LabelHistogram) and `go vet github.com/pascaldekloe/metrics` reports no errors.

**Comment by pascaldekloe** [comment]
@ceriath mentioned the `metrics_test` package might have something to do with it. It is common for examples to change package. Examples are less readable and copy–past won't work without (`metrics.`) package prefixes.

**Comment by robmuh** [comment]
Looks like GoTool is calling the tool on each individual file instead of on the directory itself. It is worth nothing that this equivalent to `go tool vet` instead of `go tool` which is deprecated for user-land usage (and broken). https://github.com/gojp/goreportcard/blob/6ecdf3c5c38cf0855cec02ab2a02ecb78b6e456f/check/go_vet.go#L21
