### ISSUE TITLE
Switch to golangci-lint from gometalinter

### ISSUE THREAD

**Issue by lahsivjar** [gojp/goreportcard#281]
[Gometalinter](https://github.com/alecthomas/gometalinter) is deprecated and archived in favor of [golangci-lint](https://github.com/golangci/golangci-lint). Is there any plan to switch to golangci-lint for reportcard too?

**Comment by shawnps** [comment]
Not at the moment - from what I can tell the license is incompatible.

**Comment by KatamariJr** [comment]
This project is unusable for newcomers as [Gometalinter](https://github.com/alecthomas/gometalinter) can no longer be built due to packages no longer existing in other repos (specifically github.com/nicksnyder/go-i18n/i18n). Either someone has to fork gometalinter and update the requirements (and document which version to fetch) or the project switches to golangci-lint.

**Comment by NITEMAN** [comment]
AFIK  golangci-lint's license has changed after this issue: https://github.com/golangci/golangci-lint/blob/master/LICENSE
