### ISSUE TITLE
Out of memory when checking format

### ISSUE THREAD

**Issue by andydotxyz** [gojp/goreportcard#299]
It seems that the Fyne theme directory may be a bit large but I don't have the error when I run locally...

An error occurred while running this test (AddError: could not parse "_repos/src/fyne.io/fyne/theme/fatal error: runtime: out of memory:1::warning: file is not gofmted with -s (gofmt)" - strconv.Atoi: parsing " runtime": invalid syntax)

https://goreportcard.com/report/fyne.io/fyne

Is there anything I can do to help resolve this? It took our score from A down to C! :(

**Comment by shawnps** [comment]
@andydotxyz yeah, looks like our server is reaching its capacity :) I re-ran the report and it seems to be back to normal.

**Comment by andydotxyz** [comment]
Thanks :)

**Comment by andydotxyz** [comment]
It happened again :( https://goreportcard.com/report/fyne.io/fyne and https://goreportcard.com/report/fyne.io/desktop

**Comment by andydotxyz** [comment]
This has happened again.
Is there something that I can do to help this stop happening?

**Comment by shawnps** [comment]
@andydotxyz There's nothing you can do on the repo itself as far as I know. It's basically because we run this app on a single small instance and we've had to push it to its limit.

A couple of weeks ago I added an in-memory cache for the badge URL lookups. But that cache only gets bigger unless we restart the app (which I just did, and then re-ran your report which now seems fixed). I might try adding timeouts to the cache entries and have a poller running in the background which purges entries > a day old or something like that.

I was recently accepted into the GitHub Sponsors program, so I might possibly be able to take donations through that on behalf of Go Report Card and upgrade the server with the money. In the meantime we do have a Patreon as well: https://www.patreon.com/goreportcard

With more servers we'd probably split it out into 2 "worker" nodes and then a memcache/redis/etc. server for the caching. It would take some time and effort to re-architect everything. Unfortunately it hasn't been feasible since we don't make enough money at the moment.

**Comment by andydotxyz** [comment]
It's happened again :-/

**Comment by sams96** [comment]
I'm getting the same error when I include large (>50MB) files (which I have because I haven't found a better way to include data files). Could you just check the file size first and ignore anything too big?
