### ISSUE TITLE
Getting 404 when I try to generate report

### ISSUE THREAD

**Issue by graywolf-at-work** [gojp/goreportcard#319]
I keep getting 404 instead of the report being generated. Steps:

1. Open https://goreportcard.com/
2. Enter `git.sr.ht/~graywolf/gomemcache` into the input field
3. Press `Generate Report`
4. Get redirected to `https://goreportcard.com/report/git.sr.ht/~graywolf/gomemcache`
5. `404 page not found`

**Comment by ancarda** [comment]
I also got this problem when I tried to analyze `git.sr.ht/~ancarda/tls-redirector`. I suspect it's because we're using SourceHut. If I had to guess, the tilde (`~`) might be causing problems.

I just made [a quick repo on GitHub](https://github.com/ancarda/a-nice-go-program), and Go Report Card was able to analyze it: https://goreportcard.com/report/github.com/ancarda/a-nice-go-program -- so it's not completely broken.

Do you have a GitLab account? Or something non-GitHub that doesn't have `~` in the URL? I wonder if that would confirm what the issue is -- as I fear it could also be that Go Report Card is hardcoded to only support GitHub.

**Comment by graywolf-at-work** [comment]
This did not magically fix itself.

**Comment by ancarda** [comment]
This issue is still relevant

**Comment by ancarda** [comment]
Might be a duplicate of #194 actually

**Comment by hermanschaaf** [comment]
Yes, this is a duplicate of #194. I believe it could be fixed by using the Go proxy to download zip files rather than using `git clone`. I'll close this as a duplicate but leave #194 open.
