### ISSUE TITLE
There was an error processing your request: Could not analyze the repository: no .go files found

### ISSUE THREAD

**Issue by AchoArnold** [gojp/goreportcard#359]
The repository has .go files all over. https://github.com/NdoleStudio/flutterwave-go

What am I doing wrongly?

![image](https://user-images.githubusercontent.com/4196457/142727168-6900851f-e9be-4f4d-819d-e92f2b695479.png)

**Comment by kozgot** [comment]
I have the same error for my repository.
![image](https://user-images.githubusercontent.com/37455584/142742114-14a90b88-1c2e-4b14-8d21-327d23b0c0bc.png)

For me, the report card was working originally without a problem as you can see on the screenshot (Last refresh: 1 week ago), but last Wednesday (17/11/2021) I could not refresh it because of this error, and it has not been fixed since. I have not changed anything in my repo or code that would cause this behaviour. The cli tool works just fine for me:
![image](https://user-images.githubusercontent.com/37455584/142742204-9977e2d7-6c95-4818-b3f4-45f951cf80af.png)

**Comment by YashdalfTheGray** [comment]
This could potentially be related to #357, have you switched your branch name recently? I think that's the problem that I'm having. 

https://goreportcard.com/report/github.com/YashdalfTheGray/colorcode

**Comment by kozgot** [comment]
No, I have not switched my branch name.

**Comment by shawnps** [comment]
@kozgot I believe your issue may be because there's no `go.mod` in the root of your repo.

The other issues are due to a case-sensitivity bug I'm investigating but unfortunately can't give any guarantees for when it will be fixed.

**Comment by shawnps** [comment]
@AchoArnold @YashdalfTheGray your repos seem to be working now, let me know if you notice any more issues 👍

**Comment by kozgot** [comment]
@shawnps, yes because this repository contains the code of 3 individual microservices, so the go.mod files are in subdirectories, however as I wrote before, the issue only occured about a week ago, before that everything worked fine. And the cli tool also works fine currently, and I have not changed the project structure, so I do not see any reason as to why this error appeared out of nowhere.

**Comment by shawnps** [comment]
@kozgot we're now using proxy.golang.org to download the latest module (as of about a week ago) which likely explains it.

**Comment by kozgot** [comment]
@shawnps Can you recommend a way to make it work again? This is a university project for me, and the due date is very close now, so I really do not want to split the code into multiple repos.

**Comment by shawnps** [comment]
@kozgot would `go mod init github.com/kozgot/go-log-processing` in the root not work?

**Comment by YashdalfTheGray** [comment]
> @AchoArnold @YashdalfTheGray your repos seem to be working now, let me know if you notice any more issues 👍

Yay! Thanks! Out of curiosity, what was the issue? No worries if you don't have time to get into it and sorry for interrupting the conversation flow.

**Comment by shawnps** [comment]
@YashdalfTheGray no worries!

The issue was: we used to use git to pull down repositories and run the checks. But we recently switched to downloading .zip files containing the module contents from proxy.golang.org.

proxy.golang.org rejects module names with uppercase letters (see the links I posted in https://github.com/gojp/goreportcard/issues/359#issuecomment-974795724). So we just needed to lowercase the module name before requesting the module contents from the proxy.

Hope that helps 👍

**Comment by kozgot** [comment]
@shawnps I did not have the time to look into it yet, but certainly will. Thank you for the suggestion.

**Comment by shawnps** [comment]
@kozgot sure, let me know how it goes.

**Comment by AchoArnold** [comment]
Its all good from my end. Can i close the ticket?

**Comment by shawnps** [comment]
@AchoArnold sure, thanks for reporting 👍

**Comment by TomiwaAribisala-git** [comment]
Hello, @shawnps  apologies for opening up this issue, I am having a similar problem generating a GoReportCard for [KubeArmor](https://github.com/kubearmor/KubeArmor) project, i must point out that the root source code does not have a `go.mod` file--going forward i intend to do `go mod https://github.com/kubearmor/KubeArmor` in the root as indicated in your [comment](https://github.com/gojp/goreportcard/issues/359#issuecomment-974833012) and see if i can generate a report card.

Also i check the project repo via proxy.golang.org, the picture output was generated below:
![download](https://github.com/gojp/goreportcard/assets/109365443/07fc4f2e-f1a2-43eb-b23d-6b3fd1418646)

I await your favorable response, thanks

**Comment by shawnps** [comment]
@TomiwaAribisala-git sorry for the late response.

Go Report Card downloads `.zip` files of source code from proxy.golang.org.

If you download this file:

http://proxy.golang.org/github.com/kubearmor/kubearmor/@v/v1.0.3.zip

You'll notice that there are no `.go` files. 

I'm not sure why that's happening, but that would be why GRC returns an error.
