### ISSUE TITLE
Allow removal of repositories that were removed/made private

### ISSUE THREAD

**Issue by alvii147** [gojp/goreportcard#424]
I recently made a repository private that I had run the go report card on while it was public. I would now like to remove the go report card data on this repository. Let me know how I can do that.

Link to report: https://goreportcard.com/report/github.com/alvii147/flagger-api

**Comment by shawnps** [comment]
@alvii147 we download packages from pkg.go.dev, and [github.com/alvii147/flagger-api](https://goreportcard.com/report/github.com/alvii147/flagger-api) is still available there. Please file a request with them to remove it and then we'll remove it on our side also:

https://pkg.go.dev/about

> If you cannot publish a new version with retractions because the source code repository or domain name is no longer accessible, or if you want to hide documentation for all current and future versions, you can [file a request](https://go.dev/s/pkgsite-package-removal) for the pkgsite team to hide your package documentation from pkg.go.dev. Note that the package will continue to be available via go get or go install unless its module is retracted.

**Comment by alvii147** [comment]
@shawnps thanks! I've filed [a request](https://github.com/golang/go/issues/67208) for that and my package has now been removed from `pkg.go.dev`. Can you remove it from go report card now? Thanks!

**Comment by shawnps** [comment]
@alvii147 sorry, I was wrong about pkg.go.dev -- we download from proxy.golang.org. The package is still available there. It looks like it can't be removed:

https://forum.golangbridge.org/t/override-or-remove-my-published-go-module/23016

So it seems like we would need to implement some sort of repo blocklist. I'm not sure when I can get around to that but I'll try to soon.

FWIW apparently since it can't be removed from proxy.golang.org, anyone could download it, and Go Report Card doesn't show any information that someone can't already get from downloading the module that way.
