### ISSUE TITLE
Add notice if github-hosted project is missing a description

### ISSUE THREAD

**Issue by client9** [gojp/goreportcard#44]
Doing some experiments I found that some repos don't have a description set in github.  It would be nice if go-reportcard mentioned this.  It might help to get people to add a description.

```
2015/10/18 17:17:56 cloudflare/gokeyless: Go implementation of the keyless protocol
2015/10/18 17:17:56 cloudflare/service:  <--- ???
2015/10/18 17:17:56 cloudflare/dns: Clone of https://github.com/miekg/dns

2015/10/18 17:17:57 coreos/coreos-metadata: A simple cloud-provider metadata agent
2015/10/18 17:17:57 coreos/fuze: Convert YAML to JSON
2015/10/18 17:17:57 coreos/mayday: <--- ???
2015/10/18 17:17:57 coreos/sqlbuilder: a SQL query composition library for Go
2015/10/18 17:17:57 coreos/discovery.etcd.io: <--- ???
2015/10/18 17:17:57 coreos/update-ssh-keys: <--- ???
2015/10/18 17:17:57 coreos/etcd-ca: <--- ???

2015/10/18 17:17:58 docker/notary: <--- ???
2015/10/18 17:17:58 docker/libcompose: <--- ???
2015/10/18 17:17:58 docker/machine: Machine management for a container-centric world
```

**Comment by shurcooL** [comment]
What if a Go package is not hosted on GitHub?

I think Go report card currently only supports Go packages hosted on github, but I hope that eventually support for all Go packages is added.

For example, consider the package [`robpike.io/filter`](https://godoc.org/robpike.io/filter). Would you rate it lower because it doesn't have a GitHub description? Or would it not apply since it's not hosted on GitHub?

I think it's important to check that the Go package has a package-level comment, but I think `golint` already checks that, doesn't it?

**Comment by client9** [comment]
hi @shurcooL .. ahh good "point".  It is a github specific issue so maybe just a "Other issues" section where it's mentioned since its not really a golang problem.  I will change the title of this issue.

hmmm interesting.
`golint` only checks for package level comment if  `-min_confidence` is 0.2 or lower!
