### ISSUE TITLE
Check: errcheck 

### ISSUE THREAD

**Issue by hermanschaaf** [gojp/goreportcard#5]
Original report by @shawnps:

[errcheck](https://github.com/kisielk/errcheck) checks whether a package is checking errors returned by functions. For example, it detects both of these:

```
recover()
```
and
```
_ := recover()
```

but unfortunately:

shawnps [9:59 PM]
but it runs at the package level :disappointed:

shawnps [9:59 PM]
and the package needs to be in your gopath too so we'd have to like clone the repo into repos/src/github.com/org/reponame and then run it on there

We could still use it but we'd have to hack the `repos` dir a bit and set `GOPATH` to it. Then we'd have to clone the GitHub repo into `repos/src/github.com/orgname/reponame` and run errcheck on there.

**Comment by shawnps** [comment]
The GOPATH thing is probably not a problem anymore, but I get a giant traceback when using errcheck locally, and then it says `error: failed to check packages: could not type check: couldn't load packages due to errors: runtime`

Will probably investigate a bit more and file an issue if I can't figure it out

**Comment by shawnps** [comment]
tried getting this working a few times but no luck...closing

**Comment by shurcooL** [comment]
Where does goreportcard clone/copy packages now, if not a GOPATH workspace?
