### ISSUE TITLE
Check: go test -cover

### ISSUE THREAD

**Issue by hermanschaaf** [gojp/goreportcard#6]
Original comment by @shawnps:

Check the coverage percent of the package. We might not do this if we can't properly sandbox stuff.

**Comment by onuryilmaz** [comment]
+1

**Comment by shurcooL** [comment]
FYI, http://gocover.io/ already does this, and it's pretty good at it.

Since `go test -cover` requires user code to be executed, gocover.io uses docker containers to do that safely.

**Comment by xor-gate** [comment]
I think the best for goreportcard could report the overall code coverage percentage? Where:

* 0 to 60% bad
* 70% good
* 80% to 100% excellent

**Comment by shurcooL** [comment]
Does gocover.io have an API? If so, perhaps it could be used to calculate the above.

If not, it's open source, so perhaps that's helpful. Otherwise, this'll need to be implemented.

**Comment by bwmarrin** [comment]
A note about this idea :)  First, I hadn't known about gocover.io before this and it looks really great.  One thing I just noticed though is while my tests depend on environment variables being set.  I might be weird in this regard but it may effect others as well.  I don't see a way to create a account on gocover.io and tell it what environment variables to setup in the docker container.  Because of that, gocover.io reports a much lower coverage than actually exists.

I say all that, because if adding it to goreportcard happened then some people might get much lower scores than they should without having many options to resolve the problem.

Best case might be getting gocover to support envars or possibly working with coveralls which I think when used with TravisCI will support envars.  I haven't tried that so I'm not sure - but I know I can set my envars on TravisCI and my tests run fine :)

**Comment by shawnps** [comment]
I'm happy to discuss this if someone wants to reopen the ticket, but I think it's safe to say now that this is outside of the scope of the value provided by Go Report Card. We have a lot of users who check very big repositories that have things like integration tests which we wouldn't be able to run with the standard `go test`.
